### ISSUE TITLE
User is logged in before I reset password.

### ISSUE THREAD

**Issue by flipfaeth** [lynndylanhurley/ng-token-auth#109]
The user is logged in after you click on the link in the reset password email, so the user can access any page whit out even change the password. For example, I can redirect the user to the index page after click the link reset password and it will show the index because the property "signedIn" is true, but actually the user should not be logged in.

**Comment by lynndylanhurley** [comment]
Hi @flipfaeth - this is expected behavior.

The process that the user goes through for password confirmation is sufficient to confirm their identity, and so the user should have full account access at that point.

If you want to prevent users from visiting other pages before changing their passwords, then that's something that should be implemented by your own client app.

**Comment by flipfaeth** [comment]
Hi @lynndylanhurley , thanks for replying.
