### ISSUE TITLE
SecurityError: when cookies are deactivated in browser

### ISSUE THREAD

**Issue by rics3n** [lynndylanhurley/ng-token-auth#124]
an uncatched error is thrown when the user deactivates cookies in the browser, resulting in a crash of the whole angular app. There was the same issue with angular-translate [#629](https://github.com/angular-translate/angular-translate/issues/629). The getSavedConfig() is throwing this error first. A try/catch block would fix it, but I would personally prefer a fallback to storing the data just in a JavaScript object. What do you think about that?

The line throwing this error is actually this one:

            if $window.localStorage

**Comment by bahoo** [comment]
I've got a similar note to share for others. When `localStorage` is disabled — most notably, in using a Private Window in Safari on Mac or iOS — it produces a `QuotaExceededError: DOM Exception 22`.

It's also worth noting that, when using this module, on any `$http`-powered request your application makes, ng-auth-token checks the contents of the response and tries to re-save the credentials, if they're included: https://github.com/lynndylanhurley/ng-token-auth/blob/d3ef20d738d05aca7a91c814f1fe288df269a063/dist/ng-token-auth.js#L647

I don't cite this as a bug in ng-token-auth, since it's just doing as advertised (and building some kind of system of checks and fallbacks could get messy in a hurry, I'm sure), but it might be worth adding a note in the docs to call out this limitation.
