### ISSUE TITLE
Wrong uid persists in header

### ISSUE THREAD

**Issue by frankjwu** [lynndylanhurley/ng-token-auth#177]
If I log into user A, log out of user A, and then log into user B in the same browser, things look fine and `validate_token` is never called (I think this is the intended behavior).

But then if I refresh the page, while still logged into user B, the new `validate_token` call will pass in user A's `uid` instead of user B's, which causes the session to switch over to user A, who should have been logged out.

Is this a bug on my end? Or is it something caused by ng-token-auth/devise-token-auth?

I'm using `config.change_headers_on_each_request = true` in my Rails configuration. I'm also logging out the user using `$auth.signOut()` in Angular.

It seems like I can fix the problem by manually deleting the `_session_id` cookie after logging out of user A and before logging into user B.

**Comment by shanbhardwaj** [comment]
+1 
I am also having exactly the same issue.

**Comment by hparfr** [comment]
+ 1

**Comment by stephenbaidu** [comment]
+1

**Comment by stephenbaidu** [comment]
Is there any quick fix for this? My users are having issues.

**Comment by stephenbaidu** [comment]
@frankjwu How did you delete the `session_id`? Tried $cookies but it does not have access to my session_id.

**Comment by ElRoberto538** [comment]
+1 This is a massive security flaw. It seems to be limited to Internet Explorer for me, Chrome appears to work fine (I haven't tested Firefox).

**Comment by lynndylanhurley** [comment]
I'll look into this ASAP.

**Comment by HanxiongShi** [comment]
I've been running into what I believe is this issue for the past couple of days. I'm using the suite of devise-token-auth and ng-token-auth along with rails-angular-resource. 

I'm not seeing this issue on Chrome, but rather on Ionic deployed to Android. The issue I'm getting is that while the original login into user B is fine, subsequent query to Rails returns a response with user A's credentials in the header. 

ex. Request:
Accept:application/json
access-token:DWCkfcne28ZagfeSbfA7iQ
client: <user b token verified on the rails side>
Content-Type:application/json
expiry:1451540800
If-Modified-Since:Mon, 26 Jul 1997 05:00:00 GMT
token-type:Bearer
uid: <user b email>
User-Agent:Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5 Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Crosswalk/15.44.384.13 Mobile Safari/537.36

Response:
Access-Token:tnXNtIXf-RoV9_Bqeldtyw
Cache-Control:max-age=0, private, must-revalidate
Client: <user A token also verified through rails console>
Connection:Keep-Alive
Content-Length:331
Content-Type:application/json; charset=utf-8
Date:Thu, 17 Dec 2015 05:47:02 GMT
Etag:W/"23a7dfb36c638d0d8dcfa434f2e4434b"
Expiry:1451540822
Server:WEBrick/1.3.1 (Ruby/2.2.2/2015-04-13)
Token-Type:Bearer
Uid: <user A email>
Vary:Origin
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Request-Id:ad9ee91d-4bfc-4913-9a91-e6502fa773d6
X-Runtime:0.188590
X-Xss-Protection:1; mode=block

This exchange promptly triggers the reponse callback and updates the header...I'm not sure why Rails / devise token auth is returning those information in the first place, and it feels like the response callback needs to be a bit smarter to avoid blindly changing the header.

**Comment by lynndylanhurley** [comment]
Have you guys tried the latest devise_token_auth beta? Please try version `0.1.37.beta4` and let me know if this is still an issue.

**Comment by HanxiongShi** [comment]
that worked for my problem! thanks!

I noticed a new forceValidateToken option in the beta release of this library as well, I was going to try that  before seeing the comment. 

thanks again for the help!

**Comment by lynndylanhurley** [comment]
Great, thanks @HanxiongShi!

**Comment by ecauli** [comment]
@lynndylanhurley I'm having  a similar problem.  When the config "config.change_headers_on_each_request = false" raises a" NoMethodError (undefined method `[]' for nil:NilClass)" #286 , Then if "config.change_headers_on_each_request = true"  not raises that , I cant login  but in next request i get "api/auth/validate_token 401 (Unauthorized)". Ow, I'm using ng-token-auth

**Comment by llaine** [comment]
I'm having the same issue as you @ecauli Have you ever manage to solve this?
