### ISSUE TITLE
Ng-token not working on Mobile Device.

### ISSUE THREAD

**Issue by alexonozor** [lynndylanhurley/ng-token-auth#282]
I am using Ng-token with Ionic which is pretty much angular on a Cordova level, I've discovered that cookies have been removed  from Android which means ng-token won't work for me here, but I will like to know if there are any way to change the users credentials to local storage instead of cookies.

**Comment by milep** [comment]
See storage config option:

the method used to persist tokens between sessions. cookies are used by default, but window.localStorage and window.sessionStorage can be used as well. A custom object can also be used. Allowed strings are cookies, localStorage, and sessionStorage, otherwise an object implementing the interface defined below

**Comment by alexonozor** [comment]
@milep Thank you very much!!

**Comment by angelxmoreno** [comment]
@alexonozor please close this if resolved

**Comment by booleanbetrayal** [comment]
Pushed v0.0.29 to NPM yesterday, @alexonozor . Should have all the flexibility in storage that you need. Hope that helps!

**Comment by alexonozor** [comment]
Do you have the doc updated @booleanbetrayal

**Comment by angelxmoreno** [comment]
@alexonozor the docs and master were already up to date.
